GET http://localhost:8000/api/cards
Accept: application/json
Content-Type: application/json
#Authorization: Basic amFuOjEyMw==
Authorization: bearer {{token}}

###
POST http://localhost:8000/api/cards/4237251412344005/operations
Accept: application/json
Content-Type: application/json
#Authorization: Basic amFuOjEyMw==
Authorization: bearer {{token}}

{
  "operationType": "INFLOW",
  "amount": 200.0,
  "currencyCode": "PLN"
}

###
POST http://localhost:8000/api/cards/4237251412344005/operations
Accept: application/json
Content-Type: application/json

{
  "operationType": "PAYMENT",
  "amount": 100.0,
  "currencyCode": "PLN"
}

###
GET http://localhost:8000/api/cards/4237251412344005/operations
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8000/api/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###
//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=password&username=jan&password=123

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}

###
//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=refresh_token&refresh_token={{ refreshToken }}

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}
