POST http://localhost:8080/articles
Accept: application/json
Content-Type: application/json
Authorization: API_KEY 1234567890

{
  "title": "Pan",
  "author": "Jan Kowalski",
  "category": "IT",
  "content": "..."
}

###

DELETE http://localhost:8080/articles/c2221f8e-f919-4986-8d94-da8116a80835
Accept: application/json
Content-Type: application/json

###

PATCH http://localhost:8080/articles/604466d8-371a-42ee-9604-eb328d9de69c
Accept: application/json
Content-Type: application/json

{
  "title": "Podstawy Spring",
  "category": "IT",
  "content": "...",
  "tags": ["it", "java"]
}

###

PUT http://localhost:8080/articles/published/604466d8-371a-42ee-9604-eb328d9de69c
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/articles/604466d8-371a-42ee-9604-eb328d9de69c
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/categories/IT/articles?tag=it&tag=java
Accept: application/json
Content-Type: application/js
